// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfQnjFT7oL5Cu9XrSSID4JPLMxwOhSlg',
    appId: '1:948749839304:web:247369bbfedbf77c4beefd',
    messagingSenderId: '948749839304',
    projectId: 'arfurniture-15455',
    authDomain: 'arfurniture-15455.firebaseapp.com',
    storageBucket: 'arfurniture-15455.firebasestorage.app',
    measurementId: 'G-1RJ1YN2CNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjWurbRJ5D-u6hAzs7kWIXHUaEhNm50oM',
    appId: '1:948749839304:android:87d3205e4776a8434beefd',
    messagingSenderId: '948749839304',
    projectId: 'arfurniture-15455',
    storageBucket: 'arfurniture-15455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO63dvUZombG8vJl2Jz2xEcSUZtCLw6mg',
    appId: '1:948749839304:ios:3955bd5103eb9fa54beefd',
    messagingSenderId: '948749839304',
    projectId: 'arfurniture-15455',
    storageBucket: 'arfurniture-15455.firebasestorage.app',
    iosBundleId: 'com.example.rootAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO63dvUZombG8vJl2Jz2xEcSUZtCLw6mg',
    appId: '1:948749839304:ios:3955bd5103eb9fa54beefd',
    messagingSenderId: '948749839304',
    projectId: 'arfurniture-15455',
    storageBucket: 'arfurniture-15455.firebasestorage.app',
    iosBundleId: 'com.example.rootAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFfQnjFT7oL5Cu9XrSSID4JPLMxwOhSlg',
    appId: '1:948749839304:web:3580427ec2e2d5b24beefd',
    messagingSenderId: '948749839304',
    projectId: 'arfurniture-15455',
    authDomain: 'arfurniture-15455.firebaseapp.com',
    storageBucket: 'arfurniture-15455.firebasestorage.app',
    measurementId: 'G-HTTXK7GT0J',
  );
}
